name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight
  workflow_dispatch: # Allows you to run this manually anytime

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch and Update TryHackMe Badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          thm_id: 'EmmanuelTanoPoku' # Replace with your TryHackMe ID
